version: "3.9"

services:
  postgres:
    container_name: "postgres"
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    env_file:
      - .envs/.local/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_backup:/backups
    networks:
      - authors_haven_network
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:5050"
    networks:
      - authors_haven_network
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    env_file:
      - .envs/.local/.postgres
      - .envs/.local/.django
    volumes:
      - .:/app:z
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - postgres
    command: /start.sh
    networks:
      - authors_haven_network
  
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - authors_haven_network
    


networks:
  authors_haven_network:
    driver: bridge

volumes:
  local_postgres_data:
  local_postgres_backup:
  static_volume:
  media_volume:
